# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Job

# Model Form Field configuration
form: $/rebel59/jobs/models/job/fields.yaml

# Model Class name
modelClass: Rebel59\Jobs\Models\Job

# Default redirect location
defaultRedirect: rebel59/jobs/jobs

# Create page
create:
    title: Create Job
    redirect: rebel59/jobs/jobs/update/:id
    redirectClose: rebel59/jobs/jobs

# Update page
update:
    title: Edit Job
    redirect: rebel59/jobs/jobs
    redirectClose: rebel59/jobs/jobs

# Preview page
preview:
    title: Preview Job
